baseURL = 'https://kvnstv1.github.io'
languageCode = 'en-us'
title = 'kvnstv1 personal site'
theme = 'hugo-sustain'

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "img/profileResized.jpg"
  author = "Kevin Steve Sathyanath"
  description = "Student of Computer Science"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "kvnstv1"
  Email         = "satke569@student.otago.ac.nz"
  LinkedIn      = "satke569"

## Main Menu
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 100
  url = "/projects/"
[[menu.main]]
  name = "Employment"
  weight = 200
  identifier = "Empoyment"
  url = "/employment/"
[[menu.main]]
  name = "Resume"
  identifier = "resume"
  weight = 300
  url = "https://kvnstv1.github.io/CV.pdf"
[[menu.main]]
  name = "About"
  identifier = "About"
  weight = 300
  url = "/About/"

[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.asciidocExt]
    backend = 'html5'
    extensions = []
    failureLevel = 'fatal'
    noHeaderOrFooter = true
    preserveTOC = false
    safeMode = 'unsafe'
    sectionNumbers = false
    trace = false
    verbose = false
    workingFolderCurrent = false
    [markup.asciidocExt.attributes]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      linkifyProtocol = 'https'
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = 'github'
      wrapStandAloneImageWithinParagraph = true
      [markup.goldmark.parser.attribute]
        block = false
        title = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokai'
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
